# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ca7166db0132c05d9ec4af051a99ab56c0330d74bf2d684882d29cb747b2b77f2a76e3b30ecc19b6d9404d934c7ed64c97e4dc1726948b7ede57dff8e7959b8

test:
  secret_key_base: ffca977e6ff21b2fd52cafc639c2d65a2cfa97346c8ef113bb89db69790636ad5fdfda8a2f042b8a48e8033878ab36585efc740cb558a75b2a95af201143f02d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
